baseURL = ""
languageCode = "en-us"
title = "OtterFi"
theme = "otter"
contentdir = "content" 
layoutdir = "layouts" 
publishdir = "public" 
canonifyurls = true 
MetaDataFormat = "toml" 
[indexes] 
    category = "categories" 
    tag = "tags" 
[author] 
    name = "James Ho" 