baseurl = "https://otterfi-jamesho.c9users.io/"
languageCode = "en-us"
title = "OtterFi"
theme = "otter"
contentdir = "content" 
layoutdir = "layouts" 
publishdir = "public" 
canonifyurls = false 
metaDataFormat = "toml" 
[taxonomies] 
    category = "categories" 
    tag = "tags" 
    color = "colors"
[author] 
    name = "James Ho" 
[params]
    ProfitColor = "#3498db"
    BudgetingColor = "#1abc9c"
    DebtColor = "#e74c3c"
    InsuranceColor = "#f39c12"
    InvestmentsColor = "#2ecc71"
    RetirementColor = "#9b59b6"