baseurl = "otterfi.com/"
languageCode = "en-us"
title = "OtterFi"
theme = "otter"
contentdir = "content" 
layoutdir = "layouts" 
publishdir = "public" 
canonifyurls = false 
metaDataFormat = "toml" 
sectionPagesMenu = "main"
[taxonomies] 
    category = ""
    tag = ""
[author] 
    name = "James Ho" 
[params]