baseurl = "https://otterfi-jamesho.c9users.io/"
languageCode = "en-us"
title = "OtterFi"
theme = "otter"
contentdir = "content" 
layoutdir = "layouts" 
publishdir = "public" 
canonifyurls = false 
metaDataFormat = "toml" 
[taxonomies] 
    category = "categories" 
    tag = "tags" 
    primarycolor = "primarycolors"
    secondarycolor = "secondarycolors"
    description = "descriptions"
[author] 
    name = "James Ho" 
[params]